spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SstuTravel;encrypt=false
spring.datasource.username=app
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.resources.static-locations=classpath:/static/



security.oauth2.client.clientId=540686726471-g02plkfk867sctmjdtir5mhblfl84gqn.apps.googleusercontent.com
security.oauth2.client.clientSecret=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
security.oauth2.client.clientAuthenticationScheme=form
security.oauth2.client.scope=openid,email,profile
security.oauth2.client.accessTokenUri=https://www.googleapis.com/oauth2/v4/token
security.oauth2.client.userAuthorizationUri=https://accounts.google.com/o/oauth2/v2/auth
security.oauth2.resource.userInfoUri=https://www.googleapis.com/oauth2/v3/userinfo
security.oauth2.resource.preferTokenInfo=true

spring.main.allow-bean-definition-overriding=true